CREATE TABLE USERS (
ID VARCHAR2(8) PRIMARY KEY,
PASSWORD VARCHAR2(8),
NAME VARCHAR2(20),
ROLE VARCHAR2(5)
)

INSERT INTO USERS(ID,PASSWORD,NAME,ROLE)
VALUES ('KIM','1234','KIMGILDONG','ADMIN')

SELECT * FROM USERS

INSERT INTO USERS(ID,PASSWORD,NAME,ROLE) 
VALUES 
('HONG','1234','GILDONG','USER'),
('PARK','1234','GILJA','USER'),
('KANG','1234','GILSUN','USER')
